/**
 * Centralized error codes for the entire application.
 * Contains application-wide error codes and per-domain error codes.
 */
export const ErrorCode = {
    // Bad Request: 400
    VALIDATION_FAILED: "VALIDATION_FAILED",
    VALIDATION_INVALID_FORMAT: "VALIDATION_INVALID_FORMAT",
    VALIDATION_MISSING_FIELD: "VALIDATION_MISSING_FIELD",
    BAD_REQUEST: "BAD_REQUEST",
    BAD_REQUEST_NO_PASSWORD_SET: "BAD_REQUEST_NO_PASSWORD_SET",
    BAD_REQUEST_PASSWORD_UNCHANGED: "BAD_REQUEST_PASSWORD_UNCHANGED",
    BAD_REQUEST_SAME_EMAIL: "BAD_REQUEST_SAME_EMAIL",
    BAD_REQUEST_SAME_PHONE: "BAD_REQUEST_SAME_PHONE",
    BAD_REQUEST_NO_PENDING_CHANGE: "BAD_REQUEST_NO_PENDING_CHANGE",

    // Authentication: 401
    AUTH_REQUIRED: "AUTH_REQUIRED",
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
    AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
    AUTH_SESSION_INVALID: "AUTH_SESSION_INVALID",
    AUTH_OTP_INVALID: "AUTH_OTP_INVALID",
    AUTH_OTP_EXPIRED: "AUTH_OTP_EXPIRED",
    AUTH_OTP_LOCKED_OUT: "AUTH_OTP_LOCKED_OUT",
    AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
    AUTH_LOGIN_LOCKED: "AUTH_LOGIN_LOCKED",
    AUTH_2FA_REQUIRED: "AUTH_2FA_REQUIRED",
    AUTH_TRANSACTIONAL_TOKEN_INVALID: "AUTH_TRANSACTIONAL_TOKEN_INVALID",
    AUTH_SIGNUP_EXPIRED: "AUTH_SIGNUP_EXPIRED",

    // Authorization: 403
    FORBIDDEN_REAUTH_REQUIRED: "FORBIDDEN_REAUTH_REQUIRED",
    FORBIDDEN_INSUFFICIENT_PERMISSION: "FORBIDDEN_INSUFFICIENT_PERMISSION",
    FORBIDDEN_RESOURCE_ACCESS: "FORBIDDEN_RESOURCE_ACCESS",

    // Resources: 404, 409
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
    RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
    RESOURCE_IN_USE: "RESOURCE_IN_USE",
    RESOURCE_DELETED: "RESOURCE_DELETED",
    CONFLICT_DELETION_PENDING: "CONFLICT_DELETION_PENDING",

    // Unprocessable Content: 422
    UNPROCESSABLE_CONTENT: "UNPROCESSABLE_CONTENT",
    INVALID_STATE: "INVALID_STATE",

    // Rate Limit: 429
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    RATE_OTP_LIMIT_EXCEEDED: "RATE_OTP_LIMIT_EXCEEDED",

    // System: 500, 502, 503
    SYSTEM_INTERNAL_ERROR: "SYSTEM_INTERNAL_ERROR",
    SYSTEM_DATABASE_ERROR: "SYSTEM_DATABASE_ERROR",
    SYSTEM_EXTERNAL_SERVICE_ERROR: "SYSTEM_EXTERNAL_SERVICE_ERROR",
    SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",

    // Upload domain
    UPLOAD_INVALID_TYPE: "UPLOAD_INVALID_TYPE",
    UPLOAD_SIZE_EXCEEDED: "UPLOAD_SIZE_EXCEEDED",
    UPLOAD_KEY_INVALID: "UPLOAD_KEY_INVALID",
    UPLOAD_PURPOSE_MISMATCH: "UPLOAD_PURPOSE_MISMATCH",

    // RBAC domain
    RBAC_SYSTEM_ROLE_IMMUTABLE: "RBAC_SYSTEM_ROLE_IMMUTABLE",
    RBAC_SYSTEM_USER_PROTECTED: "RBAC_SYSTEM_USER_PROTECTED",
    RBAC_PRIVILEGE_ESCALATION: "RBAC_PRIVILEGE_ESCALATION",
    RBAC_CANNOT_SELF_ELEVATE: "RBAC_CANNOT_SELF_ELEVATE",
    RBAC_ROLE_IN_USE: "RBAC_ROLE_IN_USE",

    // Notification domain
    NOTIFICATION_AUDIENCE_EMPTY: "NOTIFICATION_AUDIENCE_EMPTY",
    NOTIFICATION_AUDIENCE_TOO_LARGE: "NOTIFICATION_AUDIENCE_TOO_LARGE",

    // Study group domain
    STUDY_GROUP_NOT_JOINABLE: "STUDY_GROUP_NOT_JOINABLE",
    STUDY_GROUP_ALREADY_MEMBER: "STUDY_GROUP_ALREADY_MEMBER",
    STUDY_GROUP_NOT_ASSISTANT: "STUDY_GROUP_NOT_ASSISTANT",

    // Requests (join and attend)
    REQUEST_ALREADY_EXISTS: "REQUEST_ALREADY_EXISTS",
    REQUEST_WRONG_STATUS: "REQUEST_WRONG_STATUS",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
