import { Permission } from "../interfaces";

/**
 * Permission definitions.
 * Main source of truth for all permissions. Used by seeds and decorators.
 */
export const Permissions = {
    AuditLog: {
        READ: {
            key: "audit-log:read",
            resource: "audit-log",
            action: "read",
            displayName: "View Audit Logs",
            description: "View system audit logs and activity history",
            group: "System",
        },
    },

    User: {
        READ: {
            key: "user:read",
            resource: "user",
            action: "read",
            displayName: "View Users",
            description: "View user list and details",
            group: "User Management",
        },
        CREATE: {
            key: "user:create",
            resource: "user",
            action: "create",
            displayName: "Create Users",
            description: "Create user accounts",
            group: "User Management",
        },
        UPDATE: {
            key: "user:update",
            resource: "user",
            action: "update",
            displayName: "Edit Users",
            description: "Edit user profiles",
            group: "User Management",
        },
        DELETE: {
            key: "user:delete",
            resource: "user",
            action: "delete",
            displayName: "Delete Users",
            description: "Permanently delete user accounts",
            group: "User Management",
        },
        SUSPEND: {
            key: "user:suspend",
            resource: "user",
            action: "suspend",
            displayName: "Suspend Users",
            description: "Suspend and unsuspend user accounts",
            group: "User Management",
        },
    },

    Role: {
        READ: {
            key: "role:read",
            resource: "role",
            action: "read",
            displayName: "View Roles",
            description: "View roles and their permissions",
            group: "Role Management",
        },
        CREATE: {
            key: "role:create",
            resource: "role",
            action: "create",
            displayName: "Create Roles",
            description: "Create new roles",
            group: "Role Management",
        },
        UPDATE: {
            key: "role:update",
            resource: "role",
            action: "update",
            displayName: "Edit Roles",
            description: "Edit roles",
            group: "Role Management",
        },
        DELETE: {
            key: "role:delete",
            resource: "role",
            action: "delete",
            displayName: "Delete Roles",
            description: "Delete roles",
            group: "Role Management",
        },
        ASSIGN: {
            key: "role:assign",
            resource: "role",
            action: "assign",
            displayName: "Assign Roles",
            description: "Assign and remove roles to and from users",
            group: "Role Management",
        },
    },

    Upload: {
        READ: {
            key: "upload:read",
            resource: "upload",
            action: "read",
            displayName: "View Uploads",
            description: "View uploaded files list and details",
            group: "Upload Management",
        },
        DELETE: {
            key: "upload:delete",
            resource: "upload",
            action: "delete",
            displayName: "Delete Uploads",
            description: "Delete uploaded files",
            group: "Upload Management",
        },
    },

    Broadcast: {
        READ: {
            key: "broadcast:read",
            resource: "broadcast",
            action: "read",
            displayName: "View Broadcasts",
            description: "View broadcast list and details",
            group: "Notification Management",
        },
        CREATE: {
            key: "broadcast:create",
            resource: "broadcast",
            action: "create",
            displayName: "Send Broadcasts",
            description: "Compose and send broadcast notifications to users",
            group: "Notification Management",
        },
    },

    StudyGroup: {
        READ: {
            key: "study-group:read",
            resource: "study-group",
            action: "read",
            displayName: "View Study Groups",
            description: "View study groups and their details",
            group: "Teaching",
        },
        READ_ALL: {
            key: "study-group:read-all",
            resource: "study-group",
            action: "read-all",
            displayName: "View All Study Groups",
            description: "See every study group in the app, not only your own. For platform admins",
            group: "Teaching",
        },
        CREATE: {
            key: "study-group:create",
            resource: "study-group",
            action: "create",
            displayName: "Create Study Groups",
            description: "Create study groups and set their schedule and rate",
            group: "Teaching",
        },
        UPDATE: {
            key: "study-group:update",
            resource: "study-group",
            action: "update",
            displayName: "Edit Study Groups",
            description: "Edit a study group's details, schedule, and billing terms",
            group: "Teaching",
        },
        DELETE: {
            key: "study-group:delete",
            resource: "study-group",
            action: "delete",
            displayName: "Delete Study Groups",
            description: "Archive or delete study groups",
            group: "Teaching",
        },
        JOIN: {
            key: "study-group:join",
            resource: "study-group",
            action: "join",
            displayName: "Join Study Groups",
            description: "Ask to join a study group with its join code, and leave it",
            group: "Teaching",
        },
        ASSIST: {
            key: "study-group:assist",
            resource: "study-group",
            action: "assist",
            displayName: "Assist in Study Groups",
            description: "Be added to a study group as a teaching assistant",
            group: "Teaching",
        },
    },

    Enrollment: {
        READ: {
            key: "enrollment:read",
            resource: "enrollment",
            action: "read",
            displayName: "View Enrollments",
            description: "View the students enrolled in a study group",
            group: "Teaching",
        },
        CREATE: {
            key: "enrollment:create",
            resource: "enrollment",
            action: "create",
            displayName: "Enroll Students",
            description: "Add students to a study group",
            group: "Teaching",
        },
        UPDATE: {
            key: "enrollment:update",
            resource: "enrollment",
            action: "update",
            displayName: "Edit Enrollments",
            description: "Change a student's status or per-student rate override",
            group: "Teaching",
        },
        DELETE: {
            key: "enrollment:delete",
            resource: "enrollment",
            action: "delete",
            displayName: "Remove Enrollments",
            description: "Remove students from a study group",
            group: "Teaching",
        },
        APPROVE: {
            key: "enrollment:approve",
            resource: "enrollment",
            action: "approve",
            displayName: "Review Join Requests",
            description: "Approve or reject student requests to join a study group",
            group: "Teaching",
        },
    },

    StudySession: {
        READ: {
            key: "study-session:read",
            resource: "study-session",
            action: "read",
            displayName: "View Sessions",
            description: "View scheduled and past study sessions",
            group: "Teaching",
        },
        CREATE: {
            key: "study-session:create",
            resource: "study-session",
            action: "create",
            displayName: "Schedule Sessions",
            description: "Schedule study sessions or generate them from a recurrence pattern",
            group: "Teaching",
        },
        UPDATE: {
            key: "study-session:update",
            resource: "study-session",
            action: "update",
            displayName: "Edit Sessions",
            description: "Reschedule, cancel, or annotate study sessions",
            group: "Teaching",
        },
        DELETE: {
            key: "study-session:delete",
            resource: "study-session",
            action: "delete",
            displayName: "Delete Sessions",
            description: "Delete study sessions",
            group: "Teaching",
        },
        ATTEND: {
            key: "study-session:attend",
            resource: "study-session",
            action: "attend",
            displayName: "Attend Study Sessions",
            description: "Ask to attend a study session of a group you belong to",
            group: "Teaching",
        },
        APPROVE: {
            key: "study-session:approve",
            resource: "study-session",
            action: "approve",
            displayName: "Review Attend Requests",
            description: "Approve or reject student requests to attend a study session",
            group: "Teaching",
        },
    },

    Attendance: {
        READ: {
            key: "attendance:read",
            resource: "attendance",
            action: "read",
            displayName: "View Attendance",
            description: "View attendance records for a session or a student",
            group: "Teaching",
        },
        MARK: {
            key: "attendance:mark",
            resource: "attendance",
            action: "mark",
            displayName: "Mark Attendance",
            description: "Record and amend attendance for a class session",
            group: "Teaching",
        },
    },

    StudyMaterial: {
        READ: {
            key: "study-material:read",
            resource: "study-material",
            action: "read",
            displayName: "View Study Material",
            description: "View study material and its attachments",
            group: "Teaching",
        },
        CREATE: {
            key: "study-material:create",
            resource: "study-material",
            action: "create",
            displayName: "Create Study Material",
            description: "Add videos, written content, quizzes, tests, and challenges to a group",
            group: "Teaching",
        },
        UPDATE: {
            key: "study-material:update",
            resource: "study-material",
            action: "update",
            displayName: "Edit Study Material",
            description: "Edit study material and publish or unpublish it",
            group: "Teaching",
        },
        DELETE: {
            key: "study-material:delete",
            resource: "study-material",
            action: "delete",
            displayName: "Delete Study Material",
            description: "Delete study material",
            group: "Teaching",
        },
        SUBMIT: {
            key: "study-material:submit",
            resource: "study-material",
            action: "submit",
            displayName: "Submit Study Material",
            description: "Submit an assigned piece of study material for grading",
            group: "Teaching",
        },
        GRADE: {
            key: "study-material:grade",
            resource: "study-material",
            action: "grade",
            displayName: "Grade Study Material",
            description: "Score a student's submission and leave feedback",
            group: "Teaching",
        },
    },

    Invoice: {
        READ: {
            key: "invoice:read",
            resource: "invoice",
            action: "read",
            displayName: "View Invoices",
            description: "View invoices and their line items",
            group: "Billing",
        },
        CREATE: {
            key: "invoice:create",
            resource: "invoice",
            action: "create",
            displayName: "Create Invoices",
            description: "Raise invoices, including consolidated ones covering several groups",
            group: "Billing",
        },
        UPDATE: {
            key: "invoice:update",
            resource: "invoice",
            action: "update",
            displayName: "Edit Invoices",
            description: "Edit, issue, or void invoices",
            group: "Billing",
        },
        DELETE: {
            key: "invoice:delete",
            resource: "invoice",
            action: "delete",
            displayName: "Delete Invoices",
            description: "Delete draft invoices",
            group: "Billing",
        },
    },

    Payment: {
        READ: {
            key: "payment:read",
            resource: "payment",
            action: "read",
            displayName: "View Payments",
            description: "View payments recorded against an invoice",
            group: "Billing",
        },
        CREATE: {
            key: "payment:create",
            resource: "payment",
            action: "create",
            displayName: "Record Payments",
            description: "Record a cash, InstaPay, or transfer payment against an invoice",
            group: "Billing",
        },
    },
};

export const AllPermissions: Permission[] = Object.values(Permissions).flatMap((group) => Object.values(group));

export type PermissionKey = (typeof AllPermissions)[number]["key"];
